passwordRetryCache:
  ttl: 600000
  maxIdleTime: 300000
authorizationCache:
  ttl: 3600000
  maxIdleTime: 1800000
authenticationCache:
  ttl: 3600000
  maxIdleTime: 1800000
authorizationPrincipalCache:
  ttl: 3600000
  maxIdleTime: 1800000
shiro-activeSessionCache:
  ttl: 7200000
  maxIdleTime: 3600000
auth-tokenCache:
  ttl: 7200000
  maxIdleTime: 3600000
sys-config:
  ttl: 0
  maxIdleTime: 0
agile-user-remind-cache:
  ttl: 15000
  maxIdleTime: 15000
otw-new-message-count-cache:
  ttl: 7200000
  maxIdleTime: 3600000


